# Directories to lint
included:
  - ../baseapp-ios-core-v1
  - baseapp-ios-core-v1
  - Tests

# Directories to not lint
excluded:
  - Pods
  - fastlane

analyzer_rules:
  - unused_import

# Rules to enabled that aren't by default
opt_in_rules:
  - closure_spacing
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - multiline_parameters
  - overridden_super_call
  - private_outlet
  - sorted_imports
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - file_header

# Disable default rules
disabled_rules:
  - cyclomatic_complexity
  - empty_enum_arguments
  - file_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - private_over_fileprivate
  - todo
  - trailing_whitespace
  - valid_ibinspectable
  - vertical_whitespace
  - identifier_name
  - shorthand_operator
  - superfluous_disable_command
  - unused_optional_binding
  - trailing_closure
  - closure_end_indentation
  - operator_usage_whitespace
  - empty_parentheses_with_trailing_closure
  - type_name
  - generic_type_name
  - opening_brace
  - unneeded_override
  - function_name_whitespace
  - implicit_optional_initialization

# Where to report warnings and errors
reporter: "xcode"

# Customize default rules
function_parameter_count: 6
large_tuple: 4
line_length:
  warning: 200
  ignores_comments: true
type_body_length: 100
private_outlet:
  allow_private_set: true
file_header:
  required_pattern: |
                    \/\/
                    \/\/  .*?
                    \/\/  (baseapp-ios-core-v1)(.*)
                    \/\/
                    \/\/  (Created by .*? on )((\d{4}-\d{1,2}-\d{1,2})|(\d{1,2}/\d{1,2}/\d{2,4}))\.$
                    \/\/  Copyright (©|\(c\)) \d{4} SilverLogic\. All rights reserved\.
                    \/\/
