source 'https://github.com/CocoaPods/Specs.git'

target 'baseapp-ios-core-v1_Example' do
  platform :ios, '16.2'
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'baseapp-ios-core-v1', :path => '../'
  pod 'baseapp-ios-core-v1/ARKit', :path => '../'
  pod 'baseapp-ios-core-v1/FilePreviewer', :path => '../'
  pod 'SwiftLint', '~> 0.62.2'

  target 'baseapp-ios-core-v1_Tests' do
    inherit! :search_paths
  end

end

target 'Example' do
  platform :watchos, '10.4'
  use_frameworks!
  inhibit_all_warnings!

  pod 'baseapp-ios-core-v1', :path => '../'
end

target 'Example Extension' do
  platform :watchos, '10.4'
  use_frameworks!
  inhibit_all_warnings!

  pod 'baseapp-ios-core-v1', :path => '../'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
      config.build_settings['WATCHOS_DEPLOYMENT_TARGET'] = '6.2'
    end
  end
end
